### PR TITLE
Added 1 extra directory layer

### PR DESCRIPTION
**Pull request by Zen4All**
Added an extra directory layer, for quicker file access.

[Review on Reviewable](https://reviewable.io/reviews/divavocals/zen_image-handler/6)

### CODE REVIEW

**Comment by DivaVocals** [comment]
Gonna submit the new version this week.. I will not be including this pull request until I can SEE what exactly it's supposed to do and how it benefits the module.. If you can get that to me before tomorrow evening, then I can review and approve it..

**Comment by DivaVocals** [comment]
@Zen4all Hello Erik.. I am gonna have to close this pull request. Before I do that, I gotta ask once more.. I am still not seing the benefit of this additional directory layer nor have I been able to see a site with this in action. Can you please show me a site with this modification in place so I truly see it's benefit?

**Comment by Zen4All** [comment]
Better close it for now. I am still playing with this. May be I will be able to explain it better on a later date.

**Comment by DivaVocals** [comment]
Fantastic. Looking forward to seeing this complete and working..

**Comment by DivaVocals** [comment]
FYI.. just tested this to see what it really does, and as far as I can see it doesn't do anything truly valuable.. This image: 
from
bmz_cache/l/laser-lady-snowboarding.jpg.image.125x125.jpg
to 
bmz_cache/l/a/laser-lady-snowboarding.jpg.image.125x125.jpg

Which looks like it only picked up the second letter in the file name to add another folder layer.. Still not see how this might be beneficial though.. Can't wait to see how you finally shook this change out so I can understand it fully and it's potential benefit..

**Pull request closed without merging**
